/**
 * @author Lalit Sanjay Wagh <lalit.sanjaywagh@gmail.com>
 * @description App entry
 */

import React, { useEffect, useRef } from 'react';
import Head from 'next/head';

import App from './components/app/App';

const Home: React.FC = () => {
	return (
		<>
			<Head>
				<title>Lalit Sanjay Wagh</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<App />
		</>
	);
};

export default Home;
